import type { Metadata } from "next";
import "../globals.css";
import Navbar from "./components/Header/Navbar";
import Footer from "./components/Footer/Footer";

export const metadata: Metadata = {
  title: "FoodVally",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="min-h-screen">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
